-- Import bestehende Webseiten-Inhalte in die Datenbank

-- 1. Services/Dienstleistungen
INSERT INTO services (id, slug, title, description, category, image, features, pricing, sort_order, published) VALUES
(1, 'ki-chatbots-kundenservice', 'KI-Chatbots & Kundenservice', 'Intelligente 24/7 Chatbots für Webseiten, WhatsApp, Instagram und mehr. Automatisierte Kundenbetreuung, die nie schläft.', 'KI & Automation', '/service-chatbot.jpg', '["24/7 Kundensupport", "WhatsApp Integration", "Mehrsprachig", "Automatische Ticketerstellung"]', 'ab CHF 1''500', 1, true),
(2, 'whatsapp-social-media-automation', 'WhatsApp Business & Social Media Automation', 'Automatische Antworten, Broadcasts, Story-Automation und professionelle Kundenkommunikation über alle Kanäle.', 'Marketing Automation', '/service-automation.jpg', '["Automatische Follow-ups", "Broadcast-Listen", "Story-Automation", "Analytics"]', 'ab CHF 1''200', 2, true),
(3, 'web-app-entwicklung', 'Web- & App-Entwicklung', 'Moderne Webseiten, E-Commerce-Shops und mobile Apps für iOS & Android. Von der Idee bis zum Launch.', 'Development', '/service-custom-ai.jpg', '["Responsive Design", "SEO-optimiert", "Mobile Apps", "E-Commerce"]', 'ab CHF 3''000', 3, true),
(4, 'prozessautomatisierung', 'Prozessautomatisierung & Workflows', 'Zeit und Kosten sparen durch intelligente Automatisierung. Zapier, Make.com, API-Integrationen und Custom Tools.', 'Business Automation', '/service-data-analytics.jpg', '["Zapier/Make.com", "API-Integrationen", "Custom Workflows", "Zeit sparen"]', 'ab CHF 800', 4, true),
(5, 'custom-crm-software', 'Custom CRM & Business Software', 'Massgeschneiderte Lösungen für Ihr Unternehmen. CRM-Systeme, Dashboards, Verwaltungstools und Datenbanken.', 'Software Solutions', '/service-api.jpg', '["CRM-Systeme", "Custom Dashboards", "Datenbank-Design", "Business Tools"]', 'ab CHF 10''000', 5, true),
(6, 'ecommerce-online-shops', 'E-Commerce & Online-Shop Lösungen', 'Komplette Shop-Systeme mit Payment-Integration, Lagerverwaltung und Marketing-Tools. Shopify, WooCommerce oder Custom.', 'E-Commerce', '/service-consulting.jpg', '["Payment-Integration", "Lagerverwaltung", "TWINT/PostFinance", "Marketing-Tools"]', 'ab CHF 8''000', 6, true);
